// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lobby.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GameServer.Grpc.DungeonLobby {
  public static partial class DungeonLobbyService
  {
    static readonly string __ServiceName = "gameserver.lobby.v1.DungeonLobbyService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.CreateRoomRequest> __Marshaller_gameserver_lobby_v1_CreateRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.CreateRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.CreateRoomResponse> __Marshaller_gameserver_lobby_v1_CreateRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.CreateRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.GetRoomRequest> __Marshaller_gameserver_lobby_v1_GetRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.GetRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.GetRoomResponse> __Marshaller_gameserver_lobby_v1_GetRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.GetRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.GetRoomsRequest> __Marshaller_gameserver_lobby_v1_GetRoomsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.GetRoomsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.GetRoomsResponse> __Marshaller_gameserver_lobby_v1_GetRoomsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.GetRoomsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest> __Marshaller_gameserver_lobby_v1_UpdateRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse> __Marshaller_gameserver_lobby_v1_UpdateRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.JoinRoomRequest> __Marshaller_gameserver_lobby_v1_JoinRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.JoinRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.JoinRoomResponse> __Marshaller_gameserver_lobby_v1_JoinRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.JoinRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest> __Marshaller_gameserver_lobby_v1_LeaveRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse> __Marshaller_gameserver_lobby_v1_LeaveRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.StartRoomRequest> __Marshaller_gameserver_lobby_v1_StartRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.StartRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GameServer.Grpc.DungeonLobby.StartRoomResponse> __Marshaller_gameserver_lobby_v1_StartRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GameServer.Grpc.DungeonLobby.StartRoomResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.CreateRoomRequest, global::GameServer.Grpc.DungeonLobby.CreateRoomResponse> __Method_CreateRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.CreateRoomRequest, global::GameServer.Grpc.DungeonLobby.CreateRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRoom",
        __Marshaller_gameserver_lobby_v1_CreateRoomRequest,
        __Marshaller_gameserver_lobby_v1_CreateRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.GetRoomRequest, global::GameServer.Grpc.DungeonLobby.GetRoomResponse> __Method_GetRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.GetRoomRequest, global::GameServer.Grpc.DungeonLobby.GetRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRoom",
        __Marshaller_gameserver_lobby_v1_GetRoomRequest,
        __Marshaller_gameserver_lobby_v1_GetRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.GetRoomsRequest, global::GameServer.Grpc.DungeonLobby.GetRoomsResponse> __Method_GetRooms = new grpc::Method<global::GameServer.Grpc.DungeonLobby.GetRoomsRequest, global::GameServer.Grpc.DungeonLobby.GetRoomsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRooms",
        __Marshaller_gameserver_lobby_v1_GetRoomsRequest,
        __Marshaller_gameserver_lobby_v1_GetRoomsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest, global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse> __Method_UpdateRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest, global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRoom",
        __Marshaller_gameserver_lobby_v1_UpdateRoomRequest,
        __Marshaller_gameserver_lobby_v1_UpdateRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.JoinRoomRequest, global::GameServer.Grpc.DungeonLobby.JoinRoomResponse> __Method_JoinRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.JoinRoomRequest, global::GameServer.Grpc.DungeonLobby.JoinRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "JoinRoom",
        __Marshaller_gameserver_lobby_v1_JoinRoomRequest,
        __Marshaller_gameserver_lobby_v1_JoinRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest, global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse> __Method_LeaveRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest, global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LeaveRoom",
        __Marshaller_gameserver_lobby_v1_LeaveRoomRequest,
        __Marshaller_gameserver_lobby_v1_LeaveRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GameServer.Grpc.DungeonLobby.StartRoomRequest, global::GameServer.Grpc.DungeonLobby.StartRoomResponse> __Method_StartRoom = new grpc::Method<global::GameServer.Grpc.DungeonLobby.StartRoomRequest, global::GameServer.Grpc.DungeonLobby.StartRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartRoom",
        __Marshaller_gameserver_lobby_v1_StartRoomRequest,
        __Marshaller_gameserver_lobby_v1_StartRoomResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GameServer.Grpc.DungeonLobby.LobbyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DungeonLobbyService</summary>
    [grpc::BindServiceMethod(typeof(DungeonLobbyService), "BindService")]
    public abstract partial class DungeonLobbyServiceBase
    {
      /// <summary>
      /// 방 생성
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.CreateRoomResponse> CreateRoom(global::GameServer.Grpc.DungeonLobby.CreateRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 특정 방 정보 가져오기
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.GetRoomResponse> GetRoom(global::GameServer.Grpc.DungeonLobby.GetRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 방 목록 가져오기
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.GetRoomsResponse> GetRooms(global::GameServer.Grpc.DungeonLobby.GetRoomsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 방 갱신
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse> UpdateRoom(global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 방 참가
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.JoinRoomResponse> JoinRoom(global::GameServer.Grpc.DungeonLobby.JoinRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 방 떠남
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse> LeaveRoom(global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 방 시작
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GameServer.Grpc.DungeonLobby.StartRoomResponse> StartRoom(global::GameServer.Grpc.DungeonLobby.StartRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DungeonLobbyServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateRoom, serviceImpl.CreateRoom)
          .AddMethod(__Method_GetRoom, serviceImpl.GetRoom)
          .AddMethod(__Method_GetRooms, serviceImpl.GetRooms)
          .AddMethod(__Method_UpdateRoom, serviceImpl.UpdateRoom)
          .AddMethod(__Method_JoinRoom, serviceImpl.JoinRoom)
          .AddMethod(__Method_LeaveRoom, serviceImpl.LeaveRoom)
          .AddMethod(__Method_StartRoom, serviceImpl.StartRoom).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DungeonLobbyServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.CreateRoomRequest, global::GameServer.Grpc.DungeonLobby.CreateRoomResponse>(serviceImpl.CreateRoom));
      serviceBinder.AddMethod(__Method_GetRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.GetRoomRequest, global::GameServer.Grpc.DungeonLobby.GetRoomResponse>(serviceImpl.GetRoom));
      serviceBinder.AddMethod(__Method_GetRooms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.GetRoomsRequest, global::GameServer.Grpc.DungeonLobby.GetRoomsResponse>(serviceImpl.GetRooms));
      serviceBinder.AddMethod(__Method_UpdateRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.UpdateRoomRequest, global::GameServer.Grpc.DungeonLobby.UpdateRoomResponse>(serviceImpl.UpdateRoom));
      serviceBinder.AddMethod(__Method_JoinRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.JoinRoomRequest, global::GameServer.Grpc.DungeonLobby.JoinRoomResponse>(serviceImpl.JoinRoom));
      serviceBinder.AddMethod(__Method_LeaveRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.LeaveRoomRequest, global::GameServer.Grpc.DungeonLobby.LeaveRoomResponse>(serviceImpl.LeaveRoom));
      serviceBinder.AddMethod(__Method_StartRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GameServer.Grpc.DungeonLobby.StartRoomRequest, global::GameServer.Grpc.DungeonLobby.StartRoomResponse>(serviceImpl.StartRoom));
    }

  }
}
#endregion
