using System.Text;
using ClientCodegen.Models;

namespace ClientCodegen.Generators;

public static class InterfaceGenerator
{
    private const string InterfaceNamespace = "Game.Network.Https.Interfaces";

    public static void Generate(IEnumerable<ServiceModel> services, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        foreach (var service in services)
        {
            var filePath = Path.Combine(outputDir, GetTypeName(service) + ".cs");
            var content = GenerateContent(service);

            File.WriteAllText(filePath, content, Encoding.UTF8);
            Console.WriteLine($"[InterfaceGenerator] Wrote: {filePath}");
        }
    }

    public static string GenerateContent(ServiceModel service)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"// <auto-generated> Source: {service.ProtoFileName}.proto | DO NOT EDIT </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Cysharp.Threading.Tasks;");
        sb.AppendLine($"using {service.CsharpNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {InterfaceNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public interface {GetTypeName(service)}");
        sb.AppendLine("    {");

        foreach (var method in service.Methods)
        {
            sb.AppendLine($"        {GetMethodSignature(method)}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetMethodSignature(MethodModel method)
    {
        if (method.Kind == MethodKind.Unary)
        {
            return $"UniTask<{method.ResponseType}> {method.Name}Async({method.RequestType} request, CancellationToken ct = default);";
        }

        if (method.Kind == MethodKind.ServerStreaming)
        {
            return $"UniTask {method.Name}Async({method.RequestType} request, Action<{method.ResponseType}> onMessage, CancellationToken ct = default);";
        }

        if (method.Kind == MethodKind.ClientStreaming)
        {
            return $"UniTask {method.Name}Async(IObservable<{method.RequestType}> outgoing, CancellationToken ct = default);";
        }

        return $"UniTask {method.Name}Async(IObservable<{method.RequestType}> outgoing, Action<{method.ResponseType}> onMessage, CancellationToken ct = default);";
    }

    private static string GetTypeName(ServiceModel service)
    {
        return $"I{GetServiceBaseName(service.ServiceName)}GrpcService";
    }

    private static string GetServiceBaseName(string serviceName)
    {
        return serviceName.EndsWith("Service", StringComparison.Ordinal)
            ? serviceName[..^"Service".Length]
            : serviceName;
    }
}
