using System.Text;
using System.Text.RegularExpressions;

namespace ClientCodegen.Generators;

public static class PacketHandlerGenerator
{
    private const string PacketNamespace = "Game.Network.Socket.Packets";
    private const string AutoGeneratedHeader = "// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>";

    public static void Generate(string packetFilePath, string packetSerializerFilePath, string outputDir)
    {
        if (!File.Exists(packetFilePath))
        {
            Console.WriteLine($"[PacketHandlerGenerator] Packet file not found: {packetFilePath}");
            return;
        }

        if (!File.Exists(packetSerializerFilePath))
        {
            Console.WriteLine($"[PacketHandlerGenerator] Packet serializer file not found: {packetSerializerFilePath}");
            return;
        }

        var packetRootDir = Directory.GetParent(packetFilePath)?.FullName;

        if (string.IsNullOrWhiteSpace(packetRootDir))
        {
            Console.WriteLine($"[PacketHandlerGenerator] Failed to resolve packet root directory from: {packetFilePath}");
            return;
        }

        var packetDomainDir = Path.Combine(packetRootDir, "Domains");

        Directory.CreateDirectory(outputDir);

        WriteTransformedFile(packetFilePath, Path.Combine(outputDir, "Packet.cs"));
        WriteTransformedFile(packetSerializerFilePath, Path.Combine(outputDir, "PacketSerializer.cs"));

        if (!Directory.Exists(packetDomainDir))
        {
            Console.WriteLine($"[PacketHandlerGenerator] Packet domain directory not found: {packetDomainDir}");
            return;
        }

        var domainFiles = Directory.GetFiles(packetDomainDir, "*.cs", SearchOption.TopDirectoryOnly)
            .OrderBy(Path.GetFileName, StringComparer.Ordinal)
            .ToArray();

        Console.WriteLine($"[PacketHandlerGenerator] Domain packet count: {domainFiles.Length}");

        foreach (var domainFile in domainFiles)
        {
            var destinationPath = Path.Combine(outputDir, Path.GetFileName(domainFile));
            WriteTransformedFile(domainFile, destinationPath);
        }
    }

    private static void WriteTransformedFile(string sourcePath, string destinationPath)
    {
        var source = File.ReadAllText(sourcePath, Encoding.UTF8);
        var content = TransformSource(source, Path.GetFileName(sourcePath));

        File.WriteAllText(destinationPath, content, Encoding.UTF8);
        Console.WriteLine($"[PacketHandlerGenerator] Wrote: {destinationPath}");
    }

    private static string TransformSource(string source, string fileName)
    {
        var normalized = source.Replace("\r\n", "\n");

        normalized = Regex.Replace(
            normalized,
            @"^namespace\s+Shared\.Packet\.Packets\s*;",
            $"namespace {PacketNamespace}",
            RegexOptions.Multiline);

        normalized = Regex.Replace(
            normalized,
            @"^namespace\s+Shared\.Packet\s*;",
            $"namespace {PacketNamespace}",
            RegexOptions.Multiline);

        normalized = Regex.Replace(
            normalized,
            @"^using\s+Packets\s*;\s*$",
            string.Empty,
            RegexOptions.Multiline);

        if ((string.Equals(fileName, "PacketSerializer.cs", StringComparison.OrdinalIgnoreCase) ||
             normalized.Contains("ReadOnlySpan<", StringComparison.Ordinal)) &&
            !Regex.IsMatch(normalized, @"^using\s+System\s*;\s*$", RegexOptions.Multiline))
        {
            normalized = "using System;\n" + normalized;
        }

        normalized = normalized.TrimStart('\uFEFF');
        normalized = Regex.Replace(normalized, @"^\s+", string.Empty);
        normalized = ConvertToBlockScopedNamespace(normalized);
        normalized = NormalizeBlankLines(normalized);

        var builder = new StringBuilder();
        builder.AppendLine(AutoGeneratedHeader);
        builder.AppendLine();
        builder.Append(normalized);

        if (!normalized.EndsWith('\n'))
        {
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string ConvertToBlockScopedNamespace(string source)
    {
        var lines = source.Split('\n');
        var namespaceIndex = Array.FindIndex(lines, line => line.TrimStart().StartsWith("namespace ", StringComparison.Ordinal));

        if (namespaceIndex < 0)
        {
            return source;
        }

        var namespaceLine = lines[namespaceIndex].Trim();
        var namespaceName = namespaceLine["namespace ".Length..].Trim().TrimEnd(';');
        var headerLines = lines.Take(namespaceIndex).ToList();
        var bodyLines = lines.Skip(namespaceIndex + 1).ToList();

        while (headerLines.Count > 0 && string.IsNullOrWhiteSpace(headerLines[^1]))
        {
            headerLines.RemoveAt(headerLines.Count - 1);
        }

        while (bodyLines.Count > 0 && string.IsNullOrWhiteSpace(bodyLines[0]))
        {
            bodyLines.RemoveAt(0);
        }

        while (bodyLines.Count > 0 && string.IsNullOrWhiteSpace(bodyLines[^1]))
        {
            bodyLines.RemoveAt(bodyLines.Count - 1);
        }

        var builder = new StringBuilder();

        if (headerLines.Count > 0)
        {
            foreach (var headerLine in headerLines)
            {
                builder.AppendLine(headerLine);
            }

            builder.AppendLine();
        }

        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");

        foreach (var line in bodyLines)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                builder.AppendLine();
                continue;
            }

            builder.Append("    ");
            builder.AppendLine(line);
        }

        builder.AppendLine("}");
        return builder.ToString().TrimEnd();
    }

    private static string NormalizeBlankLines(string source)
    {
        var normalized = source.Replace("\r\n", "\n");
        normalized = Regex.Replace(normalized, @"\n{3,}", "\n\n");
        return normalized.TrimEnd();
    }
}
