using System.Text;
using ClientCodegen.Models;

namespace ClientCodegen.Generators;

public static class ServiceWrapperGenerator
{
    private const string ServiceNamespace = "Game.Network.Https.Services";
    private const string InterfaceNamespace = "Game.Network.Https.Interfaces";
    private const string CoreNamespace = "Game.Network.Https.Core";

    public static void Generate(IEnumerable<ServiceModel> services, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        foreach (var service in services)
        {
            var filePath = Path.Combine(outputDir, GetTypeName(service) + ".cs");
            var content = GenerateContent(service);

            File.WriteAllText(filePath, content, Encoding.UTF8);
            Console.WriteLine($"[ServiceWrapperGenerator] Wrote: {filePath}");
        }
    }

    public static string GenerateContent(ServiceModel service)
    {
        var sb = new StringBuilder();
        var wrapperName = GetTypeName(service);
        var interfaceName = $"I{GetServiceBaseName(service.ServiceName)}GrpcService";
        var grpcClientType = $"{service.ServiceName}.{service.ServiceName}Client";

        sb.AppendLine($"// <auto-generated> Source: {service.ProtoFileName}.proto | DO NOT EDIT </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Cysharp.Threading.Tasks;");
        sb.AppendLine("using Grpc.Core;");
        sb.AppendLine($"using {InterfaceNamespace};");
        sb.AppendLine($"using {CoreNamespace};");
        sb.AppendLine($"using {service.CsharpNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {ServiceNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {wrapperName} : {interfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly GrpcChannelProvider _channelProvider;");
        sb.AppendLine();
        sb.AppendLine($"        public {wrapperName}(GrpcChannelProvider channelProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _channelProvider = channelProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        private {grpcClientType} CreateClient()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {grpcClientType}(_channelProvider.CallInvoker);");
        sb.AppendLine("        }");
        sb.AppendLine();

        var hasBiDiOrClientStreaming = service.Methods.Any(m =>
            m.Kind == MethodKind.ClientStreaming || m.Kind == MethodKind.BiDi);

        for (var i = 0; i < service.Methods.Count; i++)
        {
            AppendMethod(sb, service.Methods[i]);

            if (i < service.Methods.Count - 1)
            {
                sb.AppendLine();
            }
        }

        if (hasBiDiOrClientStreaming)
        {
            sb.AppendLine();
            AppendAnonymousObserver(sb);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendMethod(StringBuilder sb, MethodModel method)
    {
        if (method.Kind == MethodKind.Unary)
        {
            sb.AppendLine($"        public async UniTask<{method.ResponseType}> {method.Name}Async({method.RequestType} request, CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var client = CreateClient();");
            sb.AppendLine($"            var call = client.{method.Name}Async(request, cancellationToken: ct);");
            sb.AppendLine("            return await call.ResponseAsync;");
            sb.AppendLine("        }");
            return;
        }

        if (method.Kind == MethodKind.ServerStreaming)
        {
            sb.AppendLine($"        public async UniTask {method.Name}Async({method.RequestType} request, Action<{method.ResponseType}> onMessage, CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var client = CreateClient();");
            sb.AppendLine($"            using var call = client.{method.Name}(request, cancellationToken: ct);");
            sb.AppendLine();
            sb.AppendLine("            await foreach (var message in call.ResponseStream.ReadAllAsync(ct))");
            sb.AppendLine("            {");
            sb.AppendLine("                onMessage(message);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            return;
        }

        if (method.Kind == MethodKind.ClientStreaming)
        {
            sb.AppendLine($"        public async UniTask {method.Name}Async(IObservable<{method.RequestType}> outgoing, CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var client = CreateClient();");
            sb.AppendLine($"            using var call = client.{method.Name}(cancellationToken: ct);");
            sb.AppendLine();
            sb.AppendLine($"            using var subscription = outgoing.Subscribe(new AnonymousObserver<{method.RequestType}>(message =>");
            sb.AppendLine("            {");
            sb.AppendLine("                call.RequestStream.WriteAsync(message).GetAwaiter().GetResult();");
            sb.AppendLine("            }));");
            sb.AppendLine();
            sb.AppendLine("            try { await call.ResponseAsync; } catch (Exception) { /* ignore or log */ }");
            sb.AppendLine("            await call.RequestStream.CompleteAsync();");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"        public async UniTask {method.Name}Async(IObservable<{method.RequestType}> outgoing, Action<{method.ResponseType}> onMessage, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            var client = CreateClient();");
        sb.AppendLine($"            using var call = client.{method.Name}(cancellationToken: ct);");
        sb.AppendLine();
        sb.AppendLine($"            using var subscription = outgoing.Subscribe(new AnonymousObserver<{method.RequestType}>(message =>");
        sb.AppendLine("            {");
        sb.AppendLine("                call.RequestStream.WriteAsync(message).GetAwaiter().GetResult();");
        sb.AppendLine("            }));");
        sb.AppendLine();
        sb.AppendLine("            await foreach (var message in call.ResponseStream.ReadAllAsync(ct))");
        sb.AppendLine("            {");
        sb.AppendLine("                onMessage(message);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            await call.RequestStream.CompleteAsync();");
        sb.AppendLine("        }");
    }

    private static void AppendAnonymousObserver(StringBuilder sb)
    {
        sb.AppendLine("        private sealed class AnonymousObserver<T> : IObserver<T>");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly Action<T> _onNext;");
        sb.AppendLine();
        sb.AppendLine("            public AnonymousObserver(Action<T> onNext) => _onNext = onNext;");
        sb.AppendLine();
        sb.AppendLine("            public void OnNext(T value) => _onNext(value);");
        sb.AppendLine("            public void OnError(Exception error) { }");
        sb.AppendLine("            public void OnCompleted() { }");
        sb.AppendLine("        }");
    }

    private static string GetTypeName(ServiceModel service)
    {
        return $"{GetServiceBaseName(service.ServiceName)}GrpcService";
    }

    private static string GetServiceBaseName(string serviceName)
    {
        return serviceName.EndsWith("Service", StringComparison.Ordinal)
            ? serviceName[..^"Service".Length]
            : serviceName;
    }
}
