// <auto-generated> Source: auth.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Auth;

namespace Game.Network.Https.Interfaces
{
    public interface IAuthGrpcService
    {
        UniTask<RegisterResponse> RegisterAsync(RegisterRequest request, CancellationToken ct = default);
        UniTask<LoginResponse> LoginAsync(LoginRequest request, CancellationToken ct = default);
        UniTask<LogoutResponse> LogoutAsync(LogoutRequest request, CancellationToken ct = default);
        UniTask<RefreshResponse> RefreshAsync(RefreshRequest request, CancellationToken ct = default);
    }
}
