// <auto-generated> Source: chat.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Chat;

namespace Game.Network.Https.Interfaces
{
    public interface IChatGrpcService
    {
        UniTask ChatStreamAsync(IObservable<ChatClientMessage> outgoing, Action<ChatServerMessage> onMessage, CancellationToken ct = default);
    }
}
