// <auto-generated> Source: codex.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Codex;

namespace Game.Network.Https.Interfaces
{
    public interface ICodexGrpcService
    {
        UniTask<GetCodexResponse> GetCodexAsync(GetCodexRequest request, CancellationToken ct = default);
    }
}
