// <auto-generated> Source: lobby.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.DungeonLobby;

namespace Game.Network.Https.Interfaces
{
    public interface IDungeonLobbyGrpcService
    {
        UniTask<CreateRoomResponse> CreateRoomAsync(CreateRoomRequest request, CancellationToken ct = default);
        UniTask<GetRoomResponse> GetRoomAsync(GetRoomRequest request, CancellationToken ct = default);
        UniTask<GetRoomsResponse> GetRoomsAsync(GetRoomsRequest request, CancellationToken ct = default);
        UniTask<UpdateRoomResponse> UpdateRoomAsync(UpdateRoomRequest request, CancellationToken ct = default);
        UniTask<JoinRoomResponse> JoinRoomAsync(JoinRoomRequest request, CancellationToken ct = default);
        UniTask<LeaveRoomResponse> LeaveRoomAsync(LeaveRoomRequest request, CancellationToken ct = default);
        UniTask<StartRoomResponse> StartRoomAsync(StartRoomRequest request, CancellationToken ct = default);
        UniTask<SetReadyResponse> SetReadyAsync(SetReadyRequest request, CancellationToken ct = default);
        UniTask SubscribeRoomAsync(SubscribeRoomRequest request, Action<SubscribeRoomResponse> onMessage, CancellationToken ct = default);
    }
}
