// <auto-generated> Source: equipment.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Equipment;

namespace Game.Network.Https.Interfaces
{
    public interface IEquipmentGrpcService
    {
        UniTask<EquipResponse> EquipAsync(EquipRequest request, CancellationToken ct = default);
        UniTask<UnequipResponse> UnequipAsync(UnequipRequest request, CancellationToken ct = default);
        UniTask<GetEquipmentResponse> GetEquipmentAsync(GetEquipmentRequest request, CancellationToken ct = default);
    }
}
