// <auto-generated> Source: inventory.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Inventory;

namespace Game.Network.Https.Interfaces
{
    public interface IInventoryGrpcService
    {
        UniTask<GetInventoryResponse> GetInventoryAsync(GetInventoryRequest request, CancellationToken ct = default);
        UniTask<ClaimKillResponse> ClaimKillAsync(ClaimKillRequest request, CancellationToken ct = default);
        UniTask<ClaimMonsterExpResponse> ClaimMonsterExpAsync(ClaimMonsterExpRequest request, CancellationToken ct = default);
        UniTask<ConsumeItemResponse> ConsumeItemAsync(ConsumeItemRequest request, CancellationToken ct = default);
    }
}
