// <auto-generated> Source: progression.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Progression;

namespace Game.Network.Https.Interfaces
{
    public interface IProgressionGrpcService
    {
        UniTask<GetProgressionResponse> GetProgressionAsync(GetProgressionRequest request, CancellationToken ct = default);
    }
}
