// <auto-generated> Source: quest.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Quest;

namespace Game.Network.Https.Interfaces
{
    public interface IQuestGrpcService
    {
        UniTask<GetQuestsResponse> GetQuestsAsync(GetQuestsRequest request, CancellationToken ct = default);
        UniTask<AcceptQuestResponse> AcceptQuestAsync(AcceptQuestRequest request, CancellationToken ct = default);
        UniTask<ClaimQuestRewardResponse> ClaimQuestRewardAsync(ClaimQuestRewardRequest request, CancellationToken ct = default);
        UniTask<ReportTalkResponse> ReportTalkAsync(ReportTalkRequest request, CancellationToken ct = default);
    }
}
