// <auto-generated> Source: shop.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Shop;

namespace Game.Network.Https.Interfaces
{
    public interface IShopGrpcService
    {
        UniTask<GetShopResponse> GetShopAsync(GetShopRequest request, CancellationToken ct = default);
        UniTask<BuyResponse> BuyAsync(BuyRequest request, CancellationToken ct = default);
        UniTask<SellResponse> SellAsync(SellRequest request, CancellationToken ct = default);
    }
}
