// <auto-generated> Source: user.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.User;

namespace Game.Network.Https.Interfaces
{
    public interface IUserGrpcService
    {
        UniTask<SetNicknameResponse> SetNickNameAsync(SetNicknameRequest request, CancellationToken ct = default);
    }
}
