// <auto-generated> Source: wallet.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameServer.Grpc.Wallet;

namespace Game.Network.Https.Interfaces
{
    public interface IWalletGrpcService
    {
        UniTask<GetWalletResponse> GetWalletAsync(GetWalletRequest request, CancellationToken ct = default);
    }
}
