using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameServer.Infrastructure.Persistence.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS users (
                    "UserId"    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    "PublicId"  character varying(10) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_PublicId" ON users ("PublicId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS user_credentials (
                    "UserId"                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Email"                  character varying(320) NOT NULL,
                    "PasswordHash"           text NOT NULL,
                    "RefreshToken"           text NULL,
                    "RefreshTokenExpiresAt"  timestamp with time zone NULL,
                    "RefreshTokenVersion"    integer NOT NULL DEFAULT 0
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_credentials_Email" ON user_credentials ("Email");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS user_profiles (
                    "UserId"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "NickName" character varying(20) NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS user_sessions (
                    "SessionId"    character varying(64) PRIMARY KEY,
                    "UserId"       bigint NOT NULL,
                    "LoginAt"      timestamp with time zone NOT NULL,
                    "LastActiveAt" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_sessions_UserId" ON user_sessions ("UserId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS dungeon_rooms (
                    "RoomId"     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    "RoomName"   text NOT NULL,
                    "HostUserId" bigint NOT NULL,
                    "MaxPlayers" integer NOT NULL,
                    "Status"     integer NOT NULL,
                    "CreatedAt"  timestamp with time zone NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS dungeon_room_players (
                    "RoomId"   bigint NOT NULL,
                    "UserId"   bigint NOT NULL,
                    "JoinedAt" timestamp with time zone NOT NULL,
                    PRIMARY KEY ("RoomId", "UserId")
                );
                CREATE INDEX IF NOT EXISTS "IX_dungeon_room_players_UserId" ON dungeon_room_players ("UserId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS game_sessions (
                    "GameSessionId" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    "RoomId"        bigint NOT NULL,
                    "SocketIp"      character varying(255) NOT NULL,
                    "SocketPort"    integer NOT NULL,
                    "Status"        integer NOT NULL,
                    "StartedAt"     timestamp with time zone NOT NULL,
                    "EndedAt"       timestamp with time zone NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_game_sessions_RoomId" ON game_sessions ("RoomId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS game_session_players (
                    "GameSessionId" bigint NOT NULL,
                    "UserId"        bigint NOT NULL,
                    "JoinedAt"      timestamp with time zone NOT NULL,
                    PRIMARY KEY ("GameSessionId", "UserId")
                );
                CREATE INDEX IF NOT EXISTS "IX_game_session_players_UserId" ON game_session_players ("UserId");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS chat_messages (
                    "MessageId"          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    "ChatType"           integer NOT NULL,
                    "Message"            character varying(1000) NOT NULL,
                    "SenderUserNickName" character varying(20) NOT NULL,
                    "TargetUserNickName" character varying(20) NULL,
                    "RoomId"             bigint NULL,
                    "SentAt"             timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_chat_messages_RoomId"             ON chat_messages ("RoomId");
                CREATE INDEX IF NOT EXISTS "IX_chat_messages_SentAt"             ON chat_messages ("SentAt");
                CREATE INDEX IF NOT EXISTS "IX_chat_messages_TargetUserNickName" ON chat_messages ("TargetUserNickName");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS outbox_messages (
                    "MessageId"   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    "Topic"       character varying(255) NOT NULL,
                    "Payload"     text NOT NULL,
                    "CreatedAt"   timestamp with time zone NOT NULL,
                    "ProcessedAt" timestamp with time zone NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_outbox_messages_ProcessedAt" ON outbox_messages ("ProcessedAt");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS outbox_messages;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS chat_messages;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS game_session_players;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS game_sessions;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS dungeon_room_players;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS dungeon_rooms;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS user_sessions;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS user_profiles;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS user_credentials;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS users;");
        }
    }
}
