syntax = "proto3";

package Protocol;
option csharp_namespace = "ServerCore.Protocol";

message Packet {
  oneof payload {
    C_Chat c_chat = 1000;  // ← 필드 번호가 사실상 PacketId
    S_Chat s_chat = 1001;
    C_CreateRoom c_createRoom = 1100;
    S_CreateRoom s_createRoom = 1101;
    C_JoinRoom c_joinRoom = 1102;
    S_JoinRoom s_joinRoom = 1103;
  }
}

message C_Chat{
  string message = 1;
}

message S_Chat{
  uint64 senderId = 1;
  string message = 2;
}

message C_CreateRoom{
  int32 max_members = 1;
}

message S_CreateRoom{
  bool success = 1;
  int32  room_id = 2;
}

message C_JoinRoom {
  int32 room_id = 1;
}

message S_JoinRoom {
  bool success = 1;
  int32 room_id = 2;
}