// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    // AuthPackets.cs
    [MemoryPackable]
    public partial class C_Auth : Packet
    {
        public long UserId { get; set; }
    }

    [MemoryPackable]
    public partial class S_Auth : Packet
    {
        public bool Success { get; set; }
        public string Message { get; set; } = "";
    }
}
