// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    /// <summary>
    /// 서버 → 클라: 던전 클리어(방의 몬스터 전멸). 서버가 전멸을 1회만 감지해 방에 브로드캐스트한다.
    /// 클라는 이 패킷을 받으면 결과 화면을 띄우고 로비 복귀 흐름으로 들어간다.
    /// 보상 산정/지급은 별개로 GameServer가 DungeonClearMessage(Redis Stream)를 소비해 처리한다.
    /// </summary>
    [MemoryPackable]
    public partial class S_DungeonClear : Packet
    {
        public long RoomId { get; set; }
    }
}
