// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    public partial class S_GameStatus: Packet
    {
        public long RoomId { get; set; }
        public EGameStatus GameStatus { get; set; }
    }

    public enum EGameStatus
    {
        WaitingForPlayers,
        InProgress,
        Finished
    }
}
