// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    // 입장/퇴장
    [MemoryPackUnion(1310, typeof(C_PlayerJoin))]
    [MemoryPackUnion(1311, typeof(S_PlayerJoined))]
    [MemoryPackUnion(1312, typeof(C_PlayerLeave))]
    [MemoryPackUnion(1313, typeof(S_PlayerLeft))]
    [MemoryPackUnion(1400,typeof(C_Ping))]
    [MemoryPackUnion(1401,typeof(S_Pong))]
    // 이동
    [MemoryPackUnion(1500,typeof(C_Move))]
    [MemoryPackUnion(1501,typeof(S_Move))]
    // 전투
    [MemoryPackUnion(1600,typeof(C_Attack))]
    [MemoryPackUnion(1601,typeof(S_Attack))]
    // 전투 - Effect(버프/디버프) 동기화
    [MemoryPackUnion(1640,typeof(S_ApplyEffect))]
    [MemoryPackUnion(1641,typeof(S_RemoveEffect))]
    // 게임 라이프사이클
    [MemoryPackUnion(1701,typeof(S_GameStatus))]
    // 던전 이벤트 - 몬스터
    [MemoryPackUnion(1810, typeof(S_SpawnMonster))]
    [MemoryPackUnion(1811, typeof(S_MonsterState))]
    [MemoryPackUnion(1812, typeof(S_MonsterDead))]
    // 던전 이벤트 - 라이프사이클(클리어/실패/결과)
    [MemoryPackUnion(1820, typeof(S_DungeonClear))]
    [MemoryPackUnion(1821, typeof(S_DungeonFailed))]
    [MemoryPackUnion(1822, typeof(C_PlayerDead))]
    public abstract partial class Packet
    {

    }
}
