// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    // 입장/퇴장
    [MemoryPackUnion(1310, typeof(C_PlayerJoin))]
    [MemoryPackUnion(1311, typeof(S_PlayerJoined))]
    [MemoryPackUnion(1312, typeof(C_PlayerLeave))]
    [MemoryPackUnion(1313, typeof(S_PlayerLeft))]
    [MemoryPackUnion(1400,typeof(C_Ping))]
    [MemoryPackUnion(1401,typeof(S_Pong))]
    // 이동
    [MemoryPackUnion(1500,typeof(C_Move))]
    [MemoryPackUnion(1501,typeof(S_Move))]
    // 전투
    [MemoryPackUnion(1600,typeof(C_Attack))]
    [MemoryPackUnion(1601,typeof(S_Attack))]
    [MemoryPackUnion(1602,typeof(C_Dodge))]
    [MemoryPackUnion(1603,typeof(S_Dodge))]
    // 전투 - Effect(버프/디버프) 동기화
    [MemoryPackUnion(1640,typeof(S_ApplyEffect))]
    [MemoryPackUnion(1641,typeof(S_RemoveEffect))]
    // 전투 - 마나 동기화(owner-only 정정)
    [MemoryPackUnion(1642,typeof(S_PlayerMana))]
    // 게임 라이프사이클
    [MemoryPackUnion(1701,typeof(S_GameStatus))]
    // 던전 이벤트 - 몬스터
    [MemoryPackUnion(1810, typeof(S_SpawnMonster))]
    [MemoryPackUnion(1811, typeof(S_MonsterState))]
    [MemoryPackUnion(1812, typeof(S_MonsterDead))]
    // 던전 이벤트 - 라이프사이클(클리어/실패/결과)
    [MemoryPackUnion(1820, typeof(S_DungeonClear))]
    [MemoryPackUnion(1821, typeof(S_DungeonFailed))]
    [MemoryPackUnion(1822, typeof(C_PlayerDead))]
    [MemoryPackUnion(1823, typeof(S_PlayerDead))]
    // 던전 이벤트 - Co-op 부활(2.5.2)
    [MemoryPackUnion(1824, typeof(C_Revive))]
    [MemoryPackUnion(1825, typeof(S_PlayerRevived))]
    // 던전 이벤트 - 루트/드랍(줍기)
    [MemoryPackUnion(1830, typeof(S_SpawnGroundItem))]
    [MemoryPackUnion(1831, typeof(S_GroundItemRemoved))]
    [MemoryPackUnion(1832, typeof(C_PickupItem))]
    [MemoryPackUnion(1833, typeof(S_ItemPickedUp))]
    public abstract partial class Packet
    {

    }
}
