// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    public partial class C_Ping : Packet
    {
        public long UserId { get; set; }
        public bool IsHealthy { get; set; } = false;
    }

    [MemoryPackable]
    public partial class S_Pong : Packet
    {
        public bool IsHealthy { get; set; } = false;
    }
}
