// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    /// <summary>
    /// 클라 → 서버: 다운된 아군 부활 요청(Co-op 2.5.2). 시전자=세션 UserId, 대상=TargetUserId.
    /// 홀드(시전 채널)는 클라가 끝낸 뒤 1회 송신. 서버가 거리·다운상태·미실패를 재검증한다(권위).
    /// </summary>
    [MemoryPackable]
    public partial class C_Revive : Packet
    {
        public long TargetUserId { get; set; }
    }

    /// <summary>
    /// 서버 → 클라(방 브로드캐스트): 부활 확정. UserId 가 다운에서 복귀, Hp 로 복구(서버 권위 수치).
    /// 로컬(자기)=제자리 부활(텔레포트 없음), 원격=다운 보존 해제(정상 캐릭터 복귀).
    /// </summary>
    [MemoryPackable]
    public partial class S_PlayerRevived : Packet
    {
        public long UserId { get; set; }
        public int Hp { get; set; }
    }
}
