// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    public partial class C_PlayerJoin : Packet
    {
        public long RoomId { get; set; }
    }

    [MemoryPackable]
    public partial class S_PlayerJoined : Packet
    {
        public bool Success { get; set; }
        public string Message { get; set; } = "";
        public long UserId { get; set; }
        public string Nickname { get; set; } = "";
        public float PosX { get; set; }
        public float PosY { get; set; }
        public float PosZ { get; set; }
        public float RotY { get; set; }
    }

    [MemoryPackable]
    public partial class C_PlayerLeave : Packet
    {
    }

    [MemoryPackable]
    public partial class S_PlayerLeft : Packet
    {
        public long UserId { get; set; }
    }
}
