// <auto-generated> Source: Shared.Packet | DO NOT EDIT </auto-generated>

using MemoryPack;

namespace Game.Network.Socket.Packets
{
    [MemoryPackable]
    public partial class C_PlayerJoin : Packet
    {
        public long RoomId  { get; set; }
        public long UserId  { get; set; }
    }

    [MemoryPackable]
    public partial class S_PlayerJoined : Packet
    {
        public bool Success { get; set; }
        public string Message { get; set; } = "";
        public long UserId { get; set; }
        public string Nickname { get; set; } = "";
        // 현재(또는 마지막으로 알려진) 위치. 이미 움직인 원격 플레이어의 위치 복원에 사용.
        public float PosX { get; set; }
        public float PosY { get; set; }
        public float PosZ { get; set; }
        public float RotY { get; set; }
        // 결정론적 스폰 입력. 클라가 MapId 레이아웃 + SpawnIndex 로 자기 스폰 위치를 직접 계산한다.
        public string MapId { get; set; } = "";
        public int SpawnIndex { get; set; }
        // 서버 권위 HP 기준선(레벨 MaxHealth). 원격 파티원 HP HUD 가 정확한 기준선에서 S_ApplyEffect 델타를 얹도록 함.
        // 몬스터(S_SpawnMonster)와 동일 패턴. Hp=현재(늦은 입장 시 이미 피해분 반영), MaxHp=상한.
        public int Hp { get; set; }
        public int MaxHp { get; set; }
    }

    [MemoryPackable]
    public partial class C_PlayerLeave : Packet
    {
    }

    [MemoryPackable]
    public partial class S_PlayerLeft : Packet
    {
        public long UserId { get; set; }
    }
}
