<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.76.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="DotNetEnv" Version="2.5.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.Graylog" Version="3.1.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Protos\" />
      <Folder Include="wwwroot\" />
    </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\GameServer.Application\GameServer.Application.csproj" />
      <ProjectReference Include="..\GameServer.Infrastructure\GameServer.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <Target Name="GenerateUnityClient" AfterTargets="Build">
      <Message Text="[ClientCodegen] Generating Unity client..." Importance="high" />
      <Exec Command="dotnet run --project &quot;$(ProjectDir)..\..\Tools\ClientCodegen\ClientCodegen.csproj&quot; -- &quot;$(ProjectDir)..\..\..&quot;"
            WorkingDirectory="$(ProjectDir)..\..\.." />
  </Target>

</Project>

