using System.Text;
using ClientCodegen.Config;

namespace ClientCodegen.Copiers;

public static class StubCopier
{
    private const string AutoGeneratedMarker = "<auto-generated>";
    private const string DoNotEditMarker = "DO NOT EDIT";

    public static void Copy(CodegenConfig config)
    {
        Console.WriteLine("[StubCopier] ===== Copy Start =====");
        Console.WriteLine($"[StubCopier] SourceDir : {config.StubSrcDir}");
        Console.WriteLine($"[StubCopier] TargetDir : {config.UnityGenDir}");

        if (!Directory.Exists(config.StubSrcDir))
        {
            Console.WriteLine("[StubCopier] Source directory not found.");
            return;
        }

        Directory.CreateDirectory(config.UnityGenDir);

        var stubFiles = Directory
            .GetFiles(config.StubSrcDir, "*.cs", SearchOption.TopDirectoryOnly)
            .Where(IsGeneratedStubFile)
            .ToList();

        Console.WriteLine($"[StubCopier] Stub file count: {stubFiles.Count}");

        foreach (var stubFile in stubFiles)
        {
            var fileName = Path.GetFileName(stubFile);
            var destinationPath = Path.Combine(config.UnityGenDir, fileName);

            File.Copy(stubFile, destinationPath, overwrite: true);
            Console.WriteLine($"[StubCopier] Copied: {fileName}");
        }

        Console.WriteLine("[StubCopier] ===== Copy End =====");
    }

    private static bool IsGeneratedStubFile(string filePath)
    {
        var fileName = Path.GetFileName(filePath);

        if (string.IsNullOrWhiteSpace(fileName))
        {
            return false;
        }

        var header = ReadFileHeader(filePath, 1);

        if (string.IsNullOrWhiteSpace(header))
        {
            return false;
        }

        var isAutoGenerated = header.Contains(AutoGeneratedMarker, StringComparison.OrdinalIgnoreCase);

        if (!isAutoGenerated)
        {
            Console.WriteLine($"[StubCopier] Skip non-stub: {fileName}");
            return false;
        }

        return true;
    }

    private static string ReadFileHeader(string filePath, int lineCount)
    {
        using var reader = new StreamReader(filePath, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);

        var lines = new List<string>();

        for (var i = 0; i < lineCount && !reader.EndOfStream; i++)
        {
            lines.Add(reader.ReadLine() ?? string.Empty);
        }

        return string.Join(Environment.NewLine, lines);
    }
}
