// <auto-generated> Source: auth.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Auth;

namespace Game.Network.Https.Services
{
    public partial class AuthGrpcService : IAuthGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public AuthGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private AuthService.AuthServiceClient CreateClient()
        {
            return new AuthService.AuthServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<RegisterResponse> RegisterAsync(RegisterRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.RegisterAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<LoginResponse> LoginAsync(LoginRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.LoginAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<LogoutResponse> LogoutAsync(LogoutRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.LogoutAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<RefreshResponse> RefreshAsync(RefreshRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.RefreshAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
