// <auto-generated> Source: chat.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Chat;

namespace Game.Network.Https.Services
{
    public partial class ChatGrpcService : IChatGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public ChatGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private ChatService.ChatServiceClient CreateClient()
        {
            return new ChatService.ChatServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask ChatStreamAsync(IObservable<ChatClientMessage> outgoing, Action<ChatServerMessage> onMessage, CancellationToken ct = default)
        {
            var client = CreateClient();
            using var call = client.ChatStream(cancellationToken: ct);

            using var subscription = outgoing.Subscribe(new AnonymousObserver<ChatClientMessage>(message =>
            {
                call.RequestStream.WriteAsync(message).GetAwaiter().GetResult();
            }));

            await foreach (var message in call.ResponseStream.ReadAllAsync(ct))
            {
                onMessage(message);
            }

            await call.RequestStream.CompleteAsync();
        }
    }
}
