// <auto-generated> Source: codex.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Codex;

namespace Game.Network.Https.Services
{
    public partial class CodexGrpcService : ICodexGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public CodexGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private CodexService.CodexServiceClient CreateClient()
        {
            return new CodexService.CodexServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetCodexResponse> GetCodexAsync(GetCodexRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetCodexAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
