// <auto-generated> Source: lobby.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.DungeonLobby;

namespace Game.Network.Https.Services
{
    public partial class DungeonLobbyGrpcService : IDungeonLobbyGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public DungeonLobbyGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private DungeonLobbyService.DungeonLobbyServiceClient CreateClient()
        {
            return new DungeonLobbyService.DungeonLobbyServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<CreateRoomResponse> CreateRoomAsync(CreateRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.CreateRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<GetRoomResponse> GetRoomAsync(GetRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<GetRoomsResponse> GetRoomsAsync(GetRoomsRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetRoomsAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<UpdateRoomResponse> UpdateRoomAsync(UpdateRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.UpdateRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<JoinRoomResponse> JoinRoomAsync(JoinRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.JoinRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<LeaveRoomResponse> LeaveRoomAsync(LeaveRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.LeaveRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<StartRoomResponse> StartRoomAsync(StartRoomRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.StartRoomAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<SetReadyResponse> SetReadyAsync(SetReadyRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.SetReadyAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask SubscribeRoomAsync(SubscribeRoomRequest request, Action<SubscribeRoomResponse> onMessage, CancellationToken ct = default)
        {
            var client = CreateClient();
            using var call = client.SubscribeRoom(request, cancellationToken: ct);

            while (await call.ResponseStream.MoveNext(ct))
            {
                onMessage(call.ResponseStream.Current);
            }
        }
    }
}
