// <auto-generated> Source: equipment.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Equipment;

namespace Game.Network.Https.Services
{
    public partial class EquipmentGrpcService : IEquipmentGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public EquipmentGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private EquipmentService.EquipmentServiceClient CreateClient()
        {
            return new EquipmentService.EquipmentServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<EquipResponse> EquipAsync(EquipRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.EquipAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<UnequipResponse> UnequipAsync(UnequipRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.UnequipAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<GetEquipmentResponse> GetEquipmentAsync(GetEquipmentRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetEquipmentAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
