// <auto-generated> Source: inventory.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Inventory;

namespace Game.Network.Https.Services
{
    public partial class InventoryGrpcService : IInventoryGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public InventoryGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private InventoryService.InventoryServiceClient CreateClient()
        {
            return new InventoryService.InventoryServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetInventoryResponse> GetInventoryAsync(GetInventoryRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetInventoryAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<ClaimKillResponse> ClaimKillAsync(ClaimKillRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.ClaimKillAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<ClaimMonsterExpResponse> ClaimMonsterExpAsync(ClaimMonsterExpRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.ClaimMonsterExpAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<ConsumeItemResponse> ConsumeItemAsync(ConsumeItemRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.ConsumeItemAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
