// <auto-generated> Source: progression.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Progression;

namespace Game.Network.Https.Services
{
    public partial class ProgressionGrpcService : IProgressionGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public ProgressionGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private ProgressionService.ProgressionServiceClient CreateClient()
        {
            return new ProgressionService.ProgressionServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetProgressionResponse> GetProgressionAsync(GetProgressionRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetProgressionAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
