// <auto-generated> Source: quest.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Quest;

namespace Game.Network.Https.Services
{
    public partial class QuestGrpcService : IQuestGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public QuestGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private QuestService.QuestServiceClient CreateClient()
        {
            return new QuestService.QuestServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetQuestsResponse> GetQuestsAsync(GetQuestsRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetQuestsAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<AcceptQuestResponse> AcceptQuestAsync(AcceptQuestRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.AcceptQuestAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<ClaimQuestRewardResponse> ClaimQuestRewardAsync(ClaimQuestRewardRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.ClaimQuestRewardAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<ReportTalkResponse> ReportTalkAsync(ReportTalkRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.ReportTalkAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
