// <auto-generated> Source: shop.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Shop;

namespace Game.Network.Https.Services
{
    public partial class ShopGrpcService : IShopGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public ShopGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private ShopService.ShopServiceClient CreateClient()
        {
            return new ShopService.ShopServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetShopResponse> GetShopAsync(GetShopRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetShopAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<BuyResponse> BuyAsync(BuyRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.BuyAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<SellResponse> SellAsync(SellRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.SellAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
