// <auto-generated> Source: user.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.User;

namespace Game.Network.Https.Services
{
    public partial class UserGrpcService : IUserGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public UserGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private UserService.UserServiceClient CreateClient()
        {
            return new UserService.UserServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<SetNicknameResponse> SetNickNameAsync(SetNicknameRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.SetNickNameAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<SavePositionResponse> SavePositionAsync(SavePositionRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.SavePositionAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }

        public async UniTask<GetLastPositionResponse> GetLastPositionAsync(GetLastPositionRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetLastPositionAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
