// <auto-generated> Source: wallet.proto | DO NOT EDIT </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using Grpc.Core;
using Game.Network.Https.Interfaces;
using Game.Network.Https.Core;
using GameServer.Grpc.Wallet;

namespace Game.Network.Https.Services
{
    public partial class WalletGrpcService : IWalletGrpcService
    {
        private readonly GrpcChannelProvider _channelProvider;

        public WalletGrpcService(GrpcChannelProvider channelProvider)
        {
            _channelProvider = channelProvider;
        }

        private WalletService.WalletServiceClient CreateClient()
        {
            return new WalletService.WalletServiceClient(_channelProvider.CallInvoker);
        }

        public async UniTask<GetWalletResponse> GetWalletAsync(GetWalletRequest request, CancellationToken ct = default)
        {
            var client = CreateClient();
            var call = client.GetWalletAsync(request, cancellationToken: ct);
            return await call.ResponseAsync;
        }
    }
}
