// <auto-generated>
// This file is automatically generated by PacketHandlerGenerator.
// DO NOT EDIT MANUALLY!
// </auto-generated>

using ServerCore.Protocol;
using UnityEngine;
using UnityEngine.Events;

namespace Game.Network.Handlers
{
    /// <summary>
    /// Common 관련 패킷 핸들러
    /// </summary>
    public class CommonPacketHandler : PacketHandler
    {
        #region Events

        public UnityEvent<S_SetNickname> OnSetNicknameReceived = new UnityEvent<S_SetNickname>();

        #endregion

        #region Handlers

        /// <summary>
        /// S_SetNickname 패킷 처리
        /// </summary>
        public void HandleSetNickname(Packet packet)
        {
            var data = packet.SSetNickname;
            Debug.Log($"[CommonHandler] SetNickname received");
            OnSetNicknameReceived?.Invoke(data);
        }

        #endregion
    }
}
