// <auto-generated>
// This file is automatically generated by PacketHandlerGenerator.
// DO NOT EDIT MANUALLY!
// </auto-generated>

using ServerCore.Protocol;
using UnityEngine;
using UnityEngine.Events;

namespace Game.Network.Handlers
{
    /// <summary>
    /// Room 관련 패킷 핸들러
    /// </summary>
    public class RoomPacketHandler : PacketHandler
    {
        #region Events

        public UnityEvent<S_CreateRoom> OnCreateRoomReceived = new UnityEvent<S_CreateRoom>();
        public UnityEvent<S_JoinRoom> OnJoinRoomReceived = new UnityEvent<S_JoinRoom>();
        public UnityEvent<S_LeaveRoom> OnLeaveRoomReceived = new UnityEvent<S_LeaveRoom>();

        #endregion

        #region Handlers

        /// <summary>
        /// S_CreateRoom 패킷 처리
        /// </summary>
        public void HandleCreateRoom(Packet packet)
        {
            var data = packet.SCreateRoom;
            Debug.Log($"[RoomHandler] CreateRoom received");
            OnCreateRoomReceived?.Invoke(data);
        }

        /// <summary>
        /// S_JoinRoom 패킷 처리
        /// </summary>
        public void HandleJoinRoom(Packet packet)
        {
            var data = packet.SJoinRoom;
            Debug.Log($"[RoomHandler] JoinRoom received");
            OnJoinRoomReceived?.Invoke(data);
        }

        /// <summary>
        /// S_LeaveRoom 패킷 처리
        /// </summary>
        public void HandleLeaveRoom(Packet packet)
        {
            var data = packet.SLeaveRoom;
            Debug.Log($"[RoomHandler] LeaveRoom received");
            OnLeaveRoomReceived?.Invoke(data);
        }

        #endregion
    }
}
