// <auto-generated>
// This file is automatically generated by PacketHandlerGenerator.
// DO NOT EDIT MANUALLY!
// </auto-generated>

using ServerCore.Protocol;
using UnityEngine;
using UnityEngine.Events;

namespace Game.Network.Handlers
{
    /// <summary>
    /// Chat 관련 패킷 핸들러
    /// </summary>
    public class ChatPacketHandler : PacketHandler
    {
        #region Events

        public UnityEvent<S_Chat> OnChatReceived = new UnityEvent<S_Chat>();

        #endregion

        #region Handlers

        /// <summary>
        /// S_Chat 패킷 처리
        /// </summary>
        public void HandleChat(Packet packet)
        {
            var data = packet.SChat;
            Debug.Log($"[ChatHandler] Chat received");
            OnChatReceived?.Invoke(data);
        }

        #endregion
    }
}
