// <auto-generated>
// This file is automatically generated by PacketHandlerGenerator.
// DO NOT EDIT MANUALLY!
// </auto-generated>

using System;
using Game.Network.Handlers;
using System.Collections.Generic;
using ServerCore.Protocol;
using UnityEngine;

namespace Game.Network.Dispatcher
{
    /// <summary>
    /// 패킷 디스패처 (자동 생성)
    /// </summary>
    public class PacketDispatcher
    {
        #region Handler Instances

        public CommonPacketHandler Common { get; private set; }
        public ChatPacketHandler Chat { get; private set; }
        public RoomPacketHandler Room { get; private set; }

        #endregion

        #region Dictionary

        private Dictionary<Packet.PayloadOneofCase, Action<Packet>> _handlers;

        #endregion

        #region Initialization

        public PacketDispatcher()
        {
            // Handler 인스턴스 생성
            Common = new CommonPacketHandler();
            Chat = new ChatPacketHandler();
            Room = new RoomPacketHandler();

            // Dictionary 초기화
            InitializeHandlers();
        }

        /// <summary>
        /// 핸들러 딕셔너리 초기화 (자동 생성)
        /// </summary>
        private void InitializeHandlers()
        {
            _handlers = new Dictionary<Packet.PayloadOneofCase, Action<Packet>>
            {
                [Packet.PayloadOneofCase.SSetNickname] = Common.HandleSetNickname,
                [Packet.PayloadOneofCase.SChat] = Chat.HandleChat,
                [Packet.PayloadOneofCase.SCreateRoom] = Room.HandleCreateRoom,
                [Packet.PayloadOneofCase.SJoinRoom] = Room.HandleJoinRoom,
                [Packet.PayloadOneofCase.SLeaveRoom] = Room.HandleLeaveRoom
            };

            Debug.Log($"[PacketDispatcher] {_handlers.Count} handlers registered");
        }

        #endregion

        #region Dispatch

        /// <summary>
        /// 패킷 디스패치
        /// </summary>
        public void Dispatch(Packet packet)
        {
            if (_handlers.TryGetValue(packet.PayloadCase, out var handler))
            {
                try
                {
                    handler(packet);
                }
                catch (Exception e)
                {
                    Debug.LogError($"[PacketDispatcher] Error: {e.Message}\n{e.StackTrace}");
                }
            }
            else
            {
                Debug.LogWarning($"[PacketDispatcher] No handler for: {packet.PayloadCase}");
            }
        }

        #endregion
    }
}
